name : test
on:
  push:
    branches: [main, staging, trying]
  pull_request:
    branches: [main]
jobs:
  gradle-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '19'
      - uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: test --info --no-daemon --stacktrace --warning-mode all
